version: "3"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raptgen
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend
    tty: true
    ports:
      - 18042:18042
    volumes:
      - ./frontend:/app
      - /etc/localtime:/etc/localtime
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn install; yarn next build; yarn next start --port 18042"

  backend:
    build:
      context: ./backend
      dockerfile: cpu.dockerfile
    container_name: backend
    tty: true
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: sh -c "uvicorn --host 0.0.0.0 api:app"

  redis:
    image: redis
    container_name: redis

  worker:
    build:
      context: ./backend
      dockerfile: cpu.dockerfile
    container_name: worker
    tty: true
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: sh -c "celery --app=tasks.celery worker --loglevel=info --pool=threads"
