version: "3"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raptgen
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  visualizer:
    build:
      context: ./visualizer
      dockerfile: dockerfile
    container_name: frontend
    tty: true
    ports:
      - 18042:18042
    volumes:
      - ./visualizer:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn install; yarn next build; yarn next start --port 18042"

  back:
    build:
      context: ./raptgen
      dockerfile: gpu.dockerfile
    container_name: backend
    tty: true
    volumes:
      - ./raptgen:/app
      - /etc/localtime:/etc/localtime
    environment:
      - PYTHONPATH=/app
    command: sh -c "uvicorn --host 0.0.0.0 api:app"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis
    container_name: redis

  worker:
    build:
      context: ./raptgen
      dockerfile: gpu.dockerfile
    container_name: worker
    tty: true
    depends_on:
      - redis
    volumes:
      - ./raptgen:/app
    environment:
      - PYTHONPATH=/app
    command: sh -c "celery --app=tasks.celery worker --loglevel=info --pool=threads"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
