import "bootswatch/dist/cosmo/bootstrap.min.css";
import "react-bootstrap-range-slider/dist/react-bootstrap-range-slider.css";

import { NextPage } from "next";
import Head from "next/head";
import Navigator from "~/components/common/navigator";
import { Card, Col, Container, Row } from "react-bootstrap";

import { useRouter } from "next/router";

const Home: React.FC = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>RaptGen Visualizer: Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigator currentPage="uploader" />
        <Container>
          <h1 style={{ marginTop: "1rem" }}>Uploader</h1>
          <hr />
          <Row>
            <Col md={4}>
              <legend>Menu</legend>
              <Card
                onClick={() => {
                  router.push("/uploader/submit-vae");
                }}
                style={{ cursor: "pointer" }}
              >
                <Card.Body>
                  <Card.Title>Upload VAE</Card.Title>
                  <Card.Text>
                    You need a trained RaptGen model file and a SELEX file.
                  </Card.Text>
                </Card.Body>
              </Card>
              <br />
              <Card
                onClick={() => {
                  router.push("/uploader/submit-gmm");
                }}
                style={{ cursor: "pointer" }}
              >
                <Card.Body>
                  <Card.Title>Upload GMM</Card.Title>
                  <Card.Text>You nead a trained GMM model file.</Card.Text>
                </Card.Body>
              </Card>
            </Col>
            <Col>Please select a menu.</Col>
          </Row>
        </Container>
      </main>
    </>
  );
};

const PageRoot: NextPage = () => {
  return <Home />;
};

export default PageRoot;
