import "bootswatch/dist/cosmo/bootstrap.min.css";
import { NextPage } from "next";
import Head from "next/head";
import { Container } from "react-bootstrap";
import Navigator from "~/components/common/navigator";
import { Provider } from "react-redux";
import { RootState, store } from "~/components/trainer/add/redux/store";
import { useSelector } from "react-redux";
import "@inovua/reactdatagrid-community/index.css";
import PageContent from "~/components/trainer/add/page-content";

const Home: React.FC = () => {
  const route = useSelector((state: RootState) => state.pageConfig.pseudoRoute);

  return (
    <>
      <Head>
        <title>RaptGen Visualizer: Trainer/add</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigator currentPage="uploader" />
        <Container>
          <h1 style={{ marginTop: "1rem" }}>Trainer</h1>
          <hr />
          <PageContent />
        </Container>
      </main>
    </>
  );
};

const PageRoot: NextPage = () => {
  return (
    <Provider store={store}>
      <Home />
    </Provider>
  );
};

export default PageRoot;
