import "bootswatch/dist/cosmo/bootstrap.min.css";
import { NextPage } from "next";
import Head from "next/head";
import { Container } from "react-bootstrap";
import Navigator from "~/components/common/navigator";
import { Provider } from "react-redux";
import { store } from "~/components/trainer/add/redux/store";
import SelexPage from "~/components/trainer/add/selex-page/selex-page";
import TrainPage from "~/components/trainer/add/train-page/train-page";
import "@inovua/reactdatagrid-community/index.css";
import { useRouter } from "next/router";

const Home: React.FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>RaptGen Visualizer: Trainer/add</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigator currentPage="uploader" />
        <Container>
          <h1 style={{ marginTop: "1rem" }}>Trainer</h1>
          <hr />
          <div
            style={{
              display: router.query.page === undefined ? "block" : "none",
            }}
          >
            <SelexPage />
          </div>
          <div
            style={{
              display: router.query.page === "raptgen" ? "block" : "none",
            }}
          >
            <TrainPage />
          </div>
        </Container>
      </main>
    </>
  );
};

const PageRoot: NextPage = () => {
  return (
    <Provider store={store}>
      <Home />
    </Provider>
  );
};

export default PageRoot;
