import "bootswatch/dist/cosmo/bootstrap.min.css";
import "react-bootstrap-range-slider/dist/react-bootstrap-range-slider.css";

import { NextPage } from "next";
import { Provider } from "react-redux";
import Head from "next/head";
import Navigator from "~/components/common/navigator";
import { Col, Container, Row } from "react-bootstrap";
// import LatentGraph from "~/components/uploader/graph/latent-graph";
import { store } from "~/components/uploader/redux/store";
// import SideBarVAE from "~/components/uploader/sidebar-vae/sidebar-vae";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>RaptGen Visualizer: Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigator currentPage="uploader" />
        <Container>
          <div className="py-2" />
          <h1>Uploader</h1>
          <hr />
          This page is under construction.
          {/* <Row>
            <Col md={4}>
              <SideBarVAE />
            </Col>
            <Col>
              <LatentGraph />
            </Col>
          </Row> */}
        </Container>
      </main>
    </>
  );
};

const PageRoot: NextPage = () => {
  return (
    <Provider store={store}>
      <Home />
    </Provider>
  );
};

export default PageRoot;
