import "bootswatch/dist/cosmo/bootstrap.min.css";
import { NextPage } from "next";
import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";
import Navigator from "~/components/common/navigator";
import "@inovua/reactdatagrid-community/index.css";
import SideBar from "~/components/gmm/home/sidebar/sidebar";
import Main from "~/components/gmm/home/main/main";
import Footer from "~/components/common/footer";

const Home: React.FC = () => {
  return (
    <div className="vh-100 d-flex flex-column">
      <Head>
        <title>RaptGen Visualizer: GMM Trainer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigator currentPage="gmm-trainer" />
      <main>
        <Container>
          <h1 style={{ marginTop: "1rem" }}>GMM Trainer</h1>
          <hr />
          <Row>
            <Col md={4}>
              <SideBar />
            </Col>
            <Col>
              <Main />
            </Col>
          </Row>
        </Container>
      </main>
      <Footer />
    </div>
  );
};

const PageRoot: NextPage = () => {
  return <Home />;
};

export default PageRoot;
