import "bootswatch/dist/cosmo/bootstrap.min.css";
import { NextPage } from "next";
import { Provider } from "react-redux";
import Head from "next/head";
import Navigator from "~/components/common/navigator";
import { Col, Container, Row, SSRProvider } from "react-bootstrap";
import "@inovua/reactdatagrid-community/index.css";

const SideBar: React.FC = () => {
  return (
    <div>
      <legend>Hello</legend>
    </div>
  );
};

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>RaptGen Visualizer: Bayesian Optimization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigator currentPage="bayesopt" />
        <Container>
          <h1 style={{ marginTop: "1rem" }}>Bayesian Optimization</h1>
          <hr />
          <Row>
            <Col md={4}>
              <SideBar />
            </Col>
            <Col>Hello world</Col>
          </Row>
        </Container>
      </main>
    </>
  );
};

const PageRoot: NextPage = () => {
  return (
    <SSRProvider>
      {/* <Provider store={store}> */}
      <Home />
      {/* </Provider> */}
    </SSRProvider>
  );
};

export default PageRoot;
