import Head from "next/head";
import { NextPage } from "next";
import 'bootswatch/dist/cosmo/bootstrap.min.css';

import { store } from "../components/store";

import { 
    Container, 
    Row,
    Col,
    Form,
    InputGroup,
    Button,
} from "react-bootstrap";

import { useState, useEffect, SetStateAction, Dispatch } from "react";

import NavRaptGen from "../components/common/NavRaptGen";
import DataSelect from "../components/data-select";
import MinCountForm from "../components/config-select";
import EncodePanel from "../components/embed-sequences";
import { Provider } from "react-redux";

import LatentGraph from "../components/latent-graph";


const SideBar = () => {

    return (
        <>
            <legend>Data</legend>
            <DataSelect />

            <legend>Config</legend>
            <MinCountForm />
            
            <legend>Operation</legend>
            <EncodePanel />

            <Form.Group className="mb-3">
                <Form.Label>Download cluster</Form.Label>
                <InputGroup>
                    <Form.Select id="clusterName" defaultValue={"all"}>
                        <option key={"a"}>all</option>
                        <option key={"b"}>b</option>
                    </Form.Select>
                    <Button id="clusterDownloadButton">Download</Button>
                </InputGroup>
            </Form.Group>

            <legend>VAE model properties</legend>
            <legend>GMM model properties</legend>
        </>
    )
}

const Footer = () => {
    return (
        <footer className="page-footer font-small blue pt-4">
            <div className="container-fluid text-center text-md-left">
                <div className="row">
                    <div className="col-md-6 mt-md-0 mt-3">
                        <h5 className="text-uppercase">Footer Content</h5>
                        <p>Here you can use rows and columns to organize your footer content.</p>
                    </div>

                    <hr className="clearfix w-100 d-md-none pb-0"/>

                    <div className="col-md-3 mb-md-0 mb-3">
                        <h5 className="text-uppercase">Links</h5>
                        <ul className="list-unstyled">
                            <li><a href="#!">Link 1</a></li>
                            <li><a href="#!">Link 2</a></li>
                            <li><a href="#!">Link 3</a></li>
                            <li><a href="#!">Link 4</a></li>
                        </ul>
                    </div>

                    <div className="col-md-3 mb-md-0 mb-3">
                        <h5 className="text-uppercase">Links</h5>
                        <ul className="list-unstyled">
                            <li><a href="#!">Link 1</a></li>
                            <li><a href="#!">Link 2</a></li>
                            <li><a href="#!">Link 3</a></li>
                            <li><a href="#!">Link 4</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div className="footer-copyright text-center py-3">© 2020 Copyright:
                <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
            </div>

        </footer>
    )
}

const VisualizerPage = () => {
    return (
      <>
        <Head>
          <title>RaptGen Visualizer</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <NavRaptGen current_page="viewer" />
          <Container>
            <h1>Viewer</h1>
            <hr />
            <Row>
                <Col md={4}>
                    <SideBar />
                </Col>
                <Col>
                    <LatentGraph />
                    {/* <PointDetail />
                    <PointTable /> */}
                </Col>
            </Row>
          </Container>
          <Footer />
        </main>
      </>
    )
  }

  const Home: NextPage = () => {
    return (
        <Provider store={store}>
            <VisualizerPage />
        </Provider>
    )
  }
  
  export default Home