import 'bootswatch/dist/cosmo/bootstrap.min.css';
import 'react-bootstrap-range-slider/dist/react-bootstrap-range-slider.css';

import { NextPage } from 'next';
import Head from "next/head";
import { Col, Row, Container } from "react-bootstrap";
import { Provider } from "react-redux";
import axios from 'axios';

import NavRaptGen from "../components/NavRaptGen";

import { store } from "../components/uploader/redux/store";

import SideBar from "../components/uploader/sidebar/sidebar";
import LatentGraph from '../components/uploader/graph/latent-graph';

axios.defaults.baseURL = 'http://localhost:8000/api';

const VisualizerPage: React.FC = () => {
    return (
        <div>
            <Head>
                <title>RaptGen Visualizer</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NavRaptGen current_page="upload_vae" />
                <Container>
                    <h1>Uploader</h1>
                    <hr />
                    <Row>
                        <Col md={4}>
                            <SideBar />
                        </Col>
                        <Col>
                            <LatentGraph />
                        </Col>
                    </Row>
                </Container>
            </main>
        </div>
    )
}

const Home: NextPage = () => {
    return (
        // <SSRProvider>
        //     <Provider store={store}>
        //         <VisualizerPage />
        //     </Provider>
        // </SSRProvider>
        <Provider store={store}>
            <VisualizerPage />
        </Provider>
    )
}

export default Home